# Generated by Django 4.1.3 on 2022-11-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_juice_alter_post_options_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juice',
            old_name='content2',
            new_name='contentT',
        ),
        migrations.RenameField(
            model_name='juice',
            old_name='postDate2',
            new_name='postDateT',
        ),
        migrations.RenameField(
            model_name='juice',
            old_name='source2',
            new_name='sourceT',
        ),
        migrations.RenameField(
            model_name='juice',
            old_name='title2',
            new_name='titleT',
        ),
    ]
