# Generated by Django 4.1.3 on 2022-11-25 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_content2_juice_contentt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='drinkHot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDrink', models.CharField(max_length=255, verbose_name='Название напитка')),
                ('newIngredients', models.TextField(verbose_name='Доп. ингридиенты')),
                ('addDateHot', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата добавления нового напитка')),
                ('priceHot', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'ГорячийНапиток',
                'verbose_name_plural': 'ГорячиеНапитки',
            },
        ),
    ]
