# Generated by Django 4.1.3 on 2022-11-25 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_drinkhot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSnack', models.CharField(max_length=255, verbose_name='Название закуска')),
                ('newSnackIngredients', models.TextField(verbose_name='Доп. ингридиенты')),
                ('addDateSnack', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата добавления нового закуска')),
                ('priceSnack', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Закуска',
                'verbose_name_plural': 'Закуски',
            },
        ),
    ]
