# Generated by Django 4.1.3 on 2022-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_snack'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на изображение'),
        ),
    ]
