# Generated by Django 4.1.3 on 2022-11-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='juice',
            name='imageJ',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на изображение'),
        ),
    ]
