# Generated by Django 4.1.3 on 2022-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_juice_imagej'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkhot',
            name='imageH',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на изображение'),
        ),
        migrations.AddField(
            model_name='snack',
            name='imageS',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на изображение'),
        ),
    ]
